### ISSUE TITLE
F_Frontでcosubscriptの値がゴミに化けることがある

### ISSUE THREAD

**Issue by hidetoshi-iwashita** [omni-compiler/omni-compiler#106]
報告者：岩下

FX100（HOKUSAI）に限って、F_Frontが誤動作します。
京でもHA-PACSでも問題なく動作しています。

sh-4.1$ cat dbg4.f90
subroutine sendp3(me)

  integer :: me(3)
  real(4), save:: buf3u(3)[*]

  buf3u(1)[me(3)-1] = 1.0

  return
end subroutine sendp3
sh-4.1$ xmpf90 --debug dbg4.f90 -c
Create __omni_tmp__/
Fortran diagnostic messages: program name(sendp3)
 Internal subprogram name(xmpf_sendp3)
  jwd2008i-i  "dbg4.f90", line 23: Dummy argument 'me' not used in this subprogram.
sh-4.1$ 

この F_Front の結果の ./__omni_tmp__/dbg4_f90_in.xml を見ると、以下のように
cosubscript "me(3)-1" がゴミの定数値に化けています。

            <arrayIndex>
              <FintConstant type="Fint">36985183</FintConstant>
            </arrayIndex>

他の環境ではこんなことはこれまでありませんでした。
以下のように正しく出ています。

            <arrayIndex>
              <minusExpr type="Fint">
                <FarrayRef type="Fint">
                  <varRef type="A23e1ab0">
                    <Var type="A23e1ab0" scope="local">me</Var>
                  </varRef>
                  <arrayIndex>
                    <FintConstant type="Fint">3</FintConstant>
                  </arrayIndex>
                </FarrayRef>
                <FintConstant type="Fint">1</FintConstant>
              </minusExpr>
            </arrayIndex>

"me(3)-1" を少し簡単な式に変えると問題なく動作します。

以上の調査から、疑わしいのは、
- F_Frontにメモリ系の潜在バグがある（解放済みメモリを参照しているなど）
- HOKUSAIのgccやyaccにバグがある

といったところでしょうか。

どなたか、思い当たることはありませんか？

**Comment by hidetoshi-iwashita** [comment]
報告者：岩下

FX100に限らず、HA-PACS（ifort）でもローカル環境（GNU）でも似た現象が起こっています。
最近のF_Frontの修正に誤りがあるようです。年末～年始くらいでしょうか。

タイトルを修正しておきます。

**Comment by h-murai** [comment]
再現待ち → クローズ
