### ISSUE TITLE
XACC/CのPGIコンパイラ利用時におけるEmpty initializerエラー

### ISSUE THREAD

**Issue by mnakao** [omni-compiler/omni-compiler#107]
環境は下記の通り。
- omnicompiler-20170301.tar.bz2
- pgi/16.10 on HA-PACS

なお、PGIコンパイラでなくgccを用いた場合は、下記に示す問題は発生しない。

下記コードでコンパイル時にエラーになる。
```C
#define	N 10
int main()
{
  double a[N], b[N], sum = 0;
#pragma acc enter data copyin(a,b)

#pragma acc parallel present(a,b)
#pragma acc loop reduction (+:sum)
  for(int i=0;i<N;i++)
    sum += a[i] + b[i];

  return 0;
}
```
 $ xmpcc test1.c -xacc
 PGC-W-0221-Redefinition of symbol _OPENACC (/work/XMPTCA/mnakao/work/xmp-trunk/include/openacc.h: 8)
 PGC-S-0155-Empty initializer not supported  (test1.c: 48)
 PGC-S-0155-Empty initializer not supported  (test1.c: 49)
 PGC/x86-64 Linux 16.10-0: compilation completed with severe errors

変換コードの48行目と49行目は下記コードである。すなわちPGIコンパイラでは、中括弧だけでは初期化に利用できないため、エラーになっている。
```C
unsigned long long _ACC_funcarg_0[] = {};
unsigned long long _ACC_funcarg_1[] = {};
```

**Comment by atabuchi** [comment]
9bd3b300 にて修正しました
