### ISSUE TITLE
Segmentation fault while using kind parameter in a parameter definition

### ISSUE THREAD

**Issue by clementval** [omni-compiler/omni-compiler#108]
```fortran
module kind1
  implicit none
  integer, parameter :: ps = 6
  integer, parameter :: rs = 37
  integer, parameter :: pd = 12
  integer, parameter :: rd = 307
  integer, parameter :: pi4 = 9
  integer, parameter :: pi8 = 14
  integer, parameter :: sp = selected_real_kind(ps,rs)
  integer, parameter :: dp = selected_real_kind(pd,rd)
  integer, parameter :: wp = dp
  integer, parameter :: i4 = selected_int_kind(pi4)
  integer, parameter :: i8 = selected_int_kind(pi8)
end module kind1
```

```fortran
module mod1
  use kind1, only: wp
  real(wp), parameter :: pi = 4. * atan(1.)
  real(wp), parameter :: ki = 1.380650e-23_wp
end module mod1
```

This code will segfault with the latest version of OMNI. the first parameter `pi` pauses no problem as the kind parameter is not used in the assignment (`_wp`). 
The second line (`ki`)  with trigger the segmentation fault.

**Comment by clementval** [comment]
This simple example is also not working. This is a regression as it was working properly before. 
```fortran
module mod1
  integer, parameter :: dp = selected_real_kind(12,37)
  integer, parameter :: wp = dp

  real(wp), parameter :: ki = 1.380650e-23_wp
end module mod1
```

```bash
"dummy.f90:mod1", line 5: bad expression in constant kind parameter
"dummy.f90:mod1", line 5: bad expression in constant kind parameter
"dummy.f90:mod1", line 5: bad constant expression in PARAMETER statement
"dummy.f90:mod1", line 6: internal error, fail to export module.
```

**Comment by clementval** [comment]
Last working revision seems to be 6f21e35122037e0a6d4bc5a5ce9a7068185447e9

**Comment by clementval** [comment]
@shingo-s @h-murai Any idea when his regression was introduced?

**Comment by clementval** [comment]
See PR #110

**Comment by h-murai** [comment]
The next commit cd122ae, which is related to module, looks suspicious. I'll ask the committer to investigate this issue.

**Comment by clementval** [comment]
@h-murai Should I do something in particular?

**Comment by h-murai** [comment]
@clementval For the present, there is no need for you to do anything. Please wait for a while.

**Comment by clementval** [comment]
@h-murai Ok, let me know if I can help in some way. This issue is kind of problematic for our code and some code at ECMWF.

**Comment by clementval** [comment]
@h-murai Any news on this issue?

**Comment by mitsuhisa-sato** [comment]
Sorry I will fix this very soon 

-- M. Sato

2017/04/05 17:52、Valentin Clement (バレンタイン クレメン) <notifications@github.com> のメッセージ:

**Comment by clementval** [comment]
This commit abd5ce15dd0638df2e49544f1276548471c67c55 fix the problem. 

I close the issue
