### ISSUE TITLE
Fcoarray素通しの問題(cobound.f90)

### ISSUE THREAD

**Issue by a-wada-rk** [omni-compiler/omni-compiler#114]
- オプション "--Wx-fnocoarray --Wf-fno-xmp-coarray"
- 現象

   tests/coarray/F/LIB/cobound.f90 において、

     allocate (a(1:2,3:5)[6:7,8:10,-3:*])

   が、

     ALLOCATE ( a ( 1 : 2 , 3 : 5 ) [ 6 : 7 ] )

   と変換される。

**Comment by h-murai** [comment]
いつの間にか直っていた → クローズ
