### ISSUE TITLE
K,FX10 実行時Abort：tests/xcalablemp/local-view/coarray/F/GET/cn1-1NGB.x 他

### ISSUE THREAD

**Issue by a-wada-rk** [omni-compiler/omni-compiler#12]
実行環境
-   K, FX10 (PCではOK)
-   omni-compiler-1.0.2 (これ以前の版でもNG)

現象
```
[RANK:0] XcalableMP runtime error: ...fatal error in XMP/F Coarray runtime
--------------------------------------------------------------------------
[mpi::mpi-api::mpi-abort]
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
CAF[1] boundary violation detected in coarray allocation
  element size 5 (name="c5      ^A^A")
```

その他
- cn2-1NGB.x, putget-2NGB.x, putget-3NGB.x, putget-6NGB.x も同様の現象。
- xmpf_traverse_initcoarray() で発生。

**Comment by hidetoshi-iwashita** [comment]
岩下です．

ファイル名にNGBと付いているテストプログラムは，京/FX10では実行できません．
制限事項です．

FJ-RDMAは４バイト境界に乗っていないデータには対応していないので，2バイト整数で長さが奇数の
配列や，長さが4の倍数でない文字列はエラーになります．

一部は実行時にエラー検出していますが，実行時に長さが決まることもあるので完全にはできません．

どうするかは要相談ですが，京などでtestsを実行する人は我々以外殆どいないでしょうから，
現状のままでいいと思いますが，どうですか？　＞みなさん

**Comment by a-wada-rk** [comment]
岩下さん

和田です。
お疲れ様です。

ご回答ありがとうございます。

- "制限事項" には、記載されていますでしょうか？
- いつもＮＧなのはうつくしくないので、TPを切り分けて、"Skipped" と出るようにするのはいかがでしょうか。

よろしくお願いいたします。

**Comment by hidetoshi-iwashita** [comment]
岩下です．

> - "制限事項" には、記載されていますでしょうか？

docs/STATUS-CAF.md に記載しpushしました．

> - いつもＮＧなのはうつくしくないので、TPを切り分けて、"Skipped" と出るようにするのはいかがでしょうか。

MakefileをMakefile.inから自動生成する方法を使えばできます．
ですが，configureから通さないとMakefileが更新されないという面倒があります．
開発中はTPを増やしたりMakefileを頻繁に修正したりしますが，その度にフルMakeなんて
やってられないので，Makefileの方を手直しして進めることになります．これはトラブルの元です．

もっとうまい方法があればそうします．
そうでなければ，現状のままとさせてください．一般ユーザが京やFX10上でmake submitを実行することは
まずないと思います．

**Comment by hidetoshi-iwashita** [comment]
隠し組込み関数
logical xmpf_coarray_uses_fjrdma()
logical xmpf_coarray_uses_mpi3_onesided()
logical xmpf_coarray_uses_gasnet()
を新設．テストプログラムの中でFJRDMAのときだけすぐにSTOPするようにした．
これで，PUTとGETのディレクトリのsubmit実行ではエラー出力ファイルのサイズが気持ちよく0になった．
