### ISSUE TITLE
XMP/Fotranでfunctionという文字列で始まる変数が利用できない

### ISSUE THREAD

**Issue by mnakao** [omni-compiler/omni-compiler#122]
> % xmpf90 --version
> Version:1.1.1, Last Commit Day:2017-03-28, Hash Value:39bddd5c

例えば、"functional"という文字列は利用できない。
```
! a.f90
program test
  implicit none
  integer :: functional
  read(*,*)  functional
end program test
```

> % xmpf90 a.f90
> "a.f90", line 4: syntax error
> "a.f90", line 4: syntax error

**Comment by mitsuhisa-sato** [comment]
I've fixed it. But, it need regression test!

**Comment by mitsuhisa-sato** [comment]
Nakao-san, please check and close this ticket.

**Comment by mnakao** [comment]
I check it. Thank you.
