### ISSUE TITLE
[F]数学関数erfc利用時の不具合

### ISSUE THREAD

**Issue by mnakao** [omni-compiler/omni-compiler#126]
> % xmpf90 --version
> Version:1.1.1, Last Commit Day:2017-03-28, Hash Value:39bddd5c

下記コードにおいて、xmpf90（PGI 16.10-0を利用）とgfortranとで出力結果が異なります。
```
program	foo
  implicit none
  real(8) :: a

  a = 1.2
  write(*,*) erfc(a)
end program foo
```
> % xmpf90 a.f90
> ./a.out
> 4.6777348E-03
>
> % gfortran a.f90
>  ./a.out
>    8.9686009022393487E-002

なお、xmpf90（GNU 4.9.2）を利用した場合、コンパイルで失敗します。
> % xmpf90 a.f90
> /tmp/__omni_tmp__7598/a_f90.o: 関数 `foo_' 内:
> a_f90_in.F90:(.text+0x5e): `erfc_' に対する定義されていない参照です
> collect2: error: ld returned 1 exit status

中間コードは下記であり、”EXTERNAL erfc”をコメントアウトすると、PGIでもGNUでも正常動作します。
```
SUBROUTINE xmpf_main ( )
 use xmpf_coarray_decl
 REAL ( KIND= 8 ) :: a
 EXTERNAL erfc
 a = 1.2
 WRITE ( unit = * , fmt = * ) erfc ( a )
99999 &
 CONTINUE
 CALL xmp_barrier ( )
END SUBROUTINE xmpf_main
```

**Comment by mitsuhisa-sato** [comment]
田渕君と同じやつね。見てみます。
さとう。

**Comment by hidetoshi-iwashita** [comment]
岩下です。

気になったのでググったりして調べました。

ERFC は Fortran2008の組込み関数のようです。

現状では「業界標準」といういいかげんな形で存在しているようです。
なので仕様は正確にはそろっていません。

PGIの実装では、ERFCとERFを組込み関数ではなくサービス関数として
提供されているようです。これはFortran2008とは非互換です。

サービス関数の場合、ユーザ定義関数と同じなので、extrinsicを書いても
書かなくても通りますが、問題はERFCが総称名関数という点です。
組込み関数なら自動的に正しい型で動作しますが、サービス関数の場合は
型宣言文がないと、ERFCは暗黙の型宣言で4バイト実数型に解釈されて、
引数のaを4バイト実数型と思って扱っていて、
そのせいで変な値を出力しているのではないかと推測します。

＃ただ、implicit noneがあるのに型宣言なしでエラーにならないのは
不思議ではあります。中間コードにはimplicit noneが出ていないので、
何かこの分析は一貫していないのでは？


On Thu, 20 Apr 2017 23:58:57 -0700
mitsuhisa-sato <notifications@github.com> wrote:

> 田渕君と同じやつね。見てみます。
> さとう。
> 
> On 2017/04/21 15:46, Masahiro Nakao wrote:
> >> % xmpf90 --version
> >> Version:1.1.1, Last Commit Day:2017-03-28, Hash Value:39bddd5c
> > 
> > 下記コードにおいて、xmpf90（PGI 16.10-0を利用）とgfortranとで出力結果が異なります。
> > ```
> > program	foo
> >    implicit none
> >    real(8) :: a
> > 
> >    a = 1.2
> >    write(*,*) erfc(a)
> > end program foo
> > ```
> >> % xmpf90 a.f90
> >> ./a.out
> >> 4.6777348E-03
> >>
> >> % gfortran a.f90
> >>   ./a.out
> >>     8.9686009022393487E-002
> > 
> > なお、xmpf90（GNU 4.9.2）を利用した場合、コンパイルで失敗します。
> >> % xmpf90 a.f90
> >> /tmp/__omni_tmp__7598/a_f90.o: 関数 `foo_' 内:
> >> a_f90_in.F90:(.text+0x5e): `erfc_' に対する定義されていない参照です
> >> collect2: error: ld returned 1 exit status
> > 
> > 中間コードは下記であり、”EXTERNAL erfc”をコメントアウトすると、PGIでもGNUでも正常動作します。
> > ```
> > SUBROUTINE xmpf_main ( )
> >   use xmpf_coarray_decl
> >   REAL ( KIND= 8 ) :: a
> >   EXTERNAL erfc
> >   a = 1.2
> >   WRITE ( unit = * , fmt = * ) erfc ( a )
> > 99999 &
> >   CONTINUE
> >   CALL xmp_barrier ( )
> > END SUBROUTINE xmpf_main
> > ```
> > 
> 
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/omni-compiler/omni-compiler/issues/126#issuecomment-296099024

岩下
hidetoshi.iwashita@riken.jp

**Comment by h-murai** [comment]
erfcに対する型宣言がない場合、以下のように正しくエラーが検出されるようになっている。

```
$ F_Front foo.f90
"foo.f90", line 6: attempt to use undefined type function, erfc
```

ただし、Fortran2008の組込み関数としては未対応。
