### ISSUE TITLE
INTRINSIC でない関数に INTRINSIC を付けると Segmentation Fault

### ISSUE THREAD

**Issue by shingo-s** [omni-compiler/omni-compiler#128]
次の例のように、INTRINSIC でない関数に INTRINSIC を指定すると Segmentation Fault で F_Front が落ちる

```fortran
program test
  implicit none
  complex :: kk
  intrinsic :: hoge

  write(*,*) hoge(kk)
end program test
```

**Comment by mitsuhisa-sato** [comment]
generate error as "unknown type of '%s' declared as intrinsic",

**Comment by h-murai** [comment]
If "implicit none" omitted in the code, the declaration of "hoge" is removed by the translator without any messages. Is it an intentional behavior?

```fortran
program test
  complex :: kk
  intrinsic :: hoge

  write(*,*) hoge(kk)
end program test
```

**Comment by shingo-s** [comment]
@h-murai 

It seems wrong behavior. I'll fix it.

**Comment by h-murai** [comment]
Now, if "implicit none" omitted in the code, REAL is added to and INTRINSIC is removed from the declaration of "hoge" and the backend compiler doesn't output no errors.
