### ISSUE TITLE
サイズ0でallocateしたcoarrayをサブルーチンに渡すとsegv

### ISSUE THREAD

**Issue by atabuchi** [omni-compiler/omni-compiler#153]
以下のように、サイズ0でallocateしたcoarrayをサブルーチンに渡すとsegvになる。 (ランタイムはMPI-3 version)
```
  real,allocatable:: ad0(:,:)[:]

  allocate(ad0(1:0,1:10)[*])   !! size zero
  call nfoo(ad0)

  nerr=0
  if (allocated(ad0)) nerr=nerr+1

  if (nerr==0) then
     print '("[",i0,"] OK")', this_image()
  else
     print '("[",i0,"] number of NGs: ",i0)', this_image(), nerr
  end if

  contains

    subroutine nfoo(d0)
      real, allocatable :: d0(:,:)[:]

      deallocate(d0)

      return
    end subroutine nfoo
  end
```
これは、tests/xcalablemp/local-view/coarray/F/MIX/autodealloc1.f90
から coarray ad1, d1 をなくしたものである。

XMPF_COARRAY_MSG=1 でデバッグしてみると
元のテストでは、サブルーチンで coarray d0 のディスクリプタを探したときに ad1 のディスクリプタを見つけていたためエラーは起きていなかった。

しかし coarray ad0 だけにすると、サブルーチンで d0 のディスクリプタを見つけられずエラーになる。

**Comment by hidetoshi-iwashita** [comment]
報告者：岩下

以下のように修正しpush

RuntimeSharing法またはRuntimeAllocation法で、coarrayの割付けサイズが０のとき、
通信ライブラリの最小単位サイズ（GASNet, MPI-3のとき1バイト、FJ-RDMAのとき4バイト）を
確保する。

RS法/GASNet、RA法/FJ-RDMAで動作確認したのでcloseします。
