### ISSUE TITLE
添字3つ組の展開の誤り

### ISSUE THREAD

**Issue by h-murai** [omni-compiler/omni-compiler#16]
配列の上下限がconstantでない場合、添字3つ組の「:」に対して、宣言時の上下限を表す変数で単純に補完してはならない。

```fortran
subroutine sub(n)
real a(n)
...
a(:) = ...
```

で、a(:)をa(1:n)に置き換えるのは誤り。a(:)のままか、a(lbound(a,1):ubound(a,1))としなければならない。

**Comment by hidetoshi-iwashita** [comment]
旧バグレポートに同じ現象があります．

http://pro-env.riken.jp/ts/guest.cgi?action=view_report&project=xmp-bts&id=353

このときは修正完了を確認したつもりでした．見落としだったか，それとも修正後の再発でしょうか？
旧レポートのテストプログラムも，今確認すると以下の通り，gfortranと違う結果を出しています．

[iwashita@localhost ~]$ cat bug5.f90 
  subroutine foo(a,n)
    real a(n)

    n=3
    write(*,*) a(2:)

  end subroutine foo

  real a(10)
  n=5
  a=1.0
  call foo(a,n)
  end
[iwashita@localhost ~]$ gfortran bug5.f90
[iwashita@localhost ~]$ a.out
   1.0000000       1.0000000       1.0000000       1.0000000    
[iwashita@localhost ~]$ xmpf90 bug5.f90
[iwashita@localhost ~]$ a.out
   1.0000000       1.0000000    
[iwashita@localhost ~]$

**Comment by h-murai** [comment]
a860cca434914040c32b0469ec639b9bc6390b3b にて修正。
