### ISSUE TITLE
Error: argument(s) mismatch for an intrinsic 'reshape()'

### ISSUE THREAD

**Issue by clementval** [omni-compiler/omni-compiler#167]
The following code will cause the error. If the function is declared before the subroutine, the error does not occur. 

```fortran
MODULE mod1
  CONTAINS

  SUBROUTINE sub1
    IMPLICIT NONE

    INTEGER :: ie, je
    INTEGER, PARAMETER :: ni = 10, nj=10, nk=10

    REAL, DIMENSION(ni,nj,nk) :: p
    REAL, POINTER :: z(:,:) => NULL()     


    z(:,:) = RESHAPE(fct_3d(p(:,:,:), ie, je, 1), (/ie, je/))

  END SUBROUTINE sub1

  FUNCTION fct_3d(p, ni, nj, nk)
    IMPLICIT NONE
    INTEGER, INTENT(in) :: ni, nj, nk
    REAL, INTENT(in), DIMENSION(ni,nj,nk) :: p
    REAL, DIMENSION(ni,nj,nk) :: fct_3d
    fct_3d = p
  END FUNCTION fct_3d

END MODULE mod1
```

```bash
"mod1.f90:mod1", line 14: argument(s) mismatch for an intrinsic 'reshape()'
```

**Comment by clementval** [comment]
Problem appears because the type of `fct_3d` is not defined correctly yet. So it's comparing `INTR_TYPE_ANY_ARRAY` with `TYPE_GNUMERIC`

**Comment by clementval** [comment]
@shingo-s I just saw that you assigned this issue to you. Are you working on a fix?

**Comment by shingo-s** [comment]
@clementval I have not work on this issue yet.

**Comment by shingo-s** [comment]
@clementval Now I start to solve this issue.

**Comment by clementval** [comment]
@shingo-s Thanks a lot. If you need any help just let me know. I can spend some time on it as well.
