### ISSUE TITLE
this_imageのエラー検出過剰

### ISSUE THREAD

**Issue by hidetoshi-iwashita** [omni-compiler/omni-compiler#17]
以下のプログラムがF_Frontでエラーになります．
この数日の修正によるレベルダウンだと思います．以前は通っていました．

[iwashita@localhost ~]$ cat z.f90 
  real a[2,2,_]
  write(_,*) this_image(dim=3,coarray=a)
  end
[iwashita@localhost ~]$ xmpf90 z.f90
"z.f90", line 2: argument(s) mismatch for an intrinsic 'this_image()'.
[iwashita@localhost ~]$ 

キーワード引数に対応していないためにエラー誤検出が起こっていると推測します．

なお，Coarray FortranのFE系のテストプログラムは
tests/xcalablemp/local-view/coarray/F/FE/
にあります．make testsで毎回通っていると思っていたのですが，そうでなかったようです．
この件が落ち着いたら omni-compiler/Makefile.in を修正して通るようにしておきます．

**Comment by h-murai** [comment]
82f23cf9f09f9e2906fd9fa2f087639b48c33e0a にて修正済み → クローズ
