### ISSUE TITLE
Cの配列代入で左辺-右辺間のデータ依存があるとき結果NG

### ISSUE THREAD

**Issue by hidetoshi-iwashita** [omni-compiler/omni-compiler#171]
報告者：岩下

XMP/Cの配列代入文
 a[1:N-1]=a[0:N-1];
の結果が期待した値と違う。
データ依存関係を無視して並び順に反復代入しているため。

例
以下のプログラムで
'''
#include<stdio.h>

#define N 5

int main()
{
  int a[N];
  int i;

  for (i=0; i<N; i++) {
    a[i]=i;
  }

  fprintf(stdout, "BEFORE\n");
  for (i=0; i<N; i++) {
    fprintf(stdout, " a[%d]=%d\n", i, a[i]);
  }

  a[1:N-1]=a[0:N-1];

  fprintf(stdout, "AFTER\n");
  for (i=0; i<N; i++) {
    fprintf(stdout, " a[%d]=%d\n", i, a[i]);
  }

  return 0;
}
'''
出力は

 BEFORE
  a[0]=0
  a[1]=1
  a[2]=2
  a[3]=3
  a[4]=4
 AFTER
  a[0]=0
  a[1]=0
  a[2]=0
  a[3]=0
  a[4]=0

同じプログラムをFortranで書くとこうなる。

 BEFORE
  a(0)=0
  a(1)=1
  a(2)=2
  a(3)=3
  a(4)=4
  a(5)=5
 AFTER
  a(0)=0
  a(1)=0
  a(2)=1
  a(3)=2
  a(4)=3
  a(5)=4

**Comment by mnakao** [comment]
@hidetoshi-iwashita 

480435でFixしましたので、ご確認をお願い致します。

**Comment by hidetoshi-iwashita** [comment]
確認しました。issueを閉じます。
