### ISSUE TITLE
ERRORSTOP 文の処理方法を決める

### ISSUE THREAD

**Issue by shingo-s** [omni-compiler/omni-compiler#174]
5c27ec8 の F-FrontEnd では `ERROR STOP` を `CALL xmpf_error_stop()` に置き換えている。

この実装をやめて `ERROR STOP` を `ERROR STOP` にするか、条件付きでこの実装を残すかなどを決定する必要がある。

なお `xmpf_error_stop()` への置き換えは 8aa250ce で導入された。

**Comment by h-murai** [comment]
@shingo-s 既存の実装は捨てて、ERROR STOP 文に対応する新しい XcodeML タグを導入する方針にします。
