### ISSUE TITLE
interface block内でuseしたモジュールのparameter変数

### ISSUE THREAD

**Issue by hidetoshi-iwashita** [omni-compiler/omni-compiler#176]
報告者：岩下

以下のパターンで、トランスレータ出力が異常。

module moo
  integer,parameter :: m=5
end module moo

subroutine caller
  interface
     subroutine foo(a)
       use moo
       real a(m)
     end subroutine foo
  end interface

end subroutine caller

以下のように、Fortranでエラーになります。

[iwashita@localhost sample]$ xmpf90 bug1.f90 --debug
xmpf90 bug1.f90 --debug
bug1.f90:2.27:

   INTEGER , PARAMETER :: m = 5
                           1
Error: Symbol 'm' at (1) already has basic type of INTEGER
[iwashita@localhost sample]$ 

トランスレータの出力を見ると、interface block内のuse文の下に、余計な１行が出ています。
（読み易くするため#-line行は削除）

SUBROUTINE caller ( )
 use xmpf_coarray_decl
 INTERFACE
  SUBROUTINE foo ( a )
   USE moo
   INTEGER , PARAMETER :: m = 5

   REAL :: a ( 1 : 5 )

  END SUBROUTINE foo
 END INTERFACE

99999 &
 CONTINUE
END SUBROUTINE caller

**Comment by h-murai** [comment]
fixed before I realized.
