### ISSUE TITLE
[F] allocatableなCoarrayの実行時エラー

### ISSUE THREAD

**Issue by mnakao** [omni-compiler/omni-compiler#179]
環境
- HA-PACS上のmvapichのみでエラー
- omnicompiler-20170718

> $ module list
> Currently Loaded Modulefiles:
>  1) pgi/17.3                       2) cuda/8.0.44                    3) mvapich2/2.2_pgi_cuda-8.0.44

```Fortran
program test
 real(8),allocatable :: A(:,:)[:]
 allocate(A(3,5)[*])
 A(:,:) = 0.d0
end program test
```

> $ xmpf90 -mcmodel=medium  test.f90
> 
> $ cat submit.sh
> #PBS -S /bin/bash
> #PBS -N XMP_NICAM_DC
> #PBS -A XMPTCA
> #PBS -q tcaq
> #PBS -l select=1:ncpus=1:mpiprocs=1
> #PBS -l walltime=00:03:00
> 
> . /opt/Modules/default/init/bash
> 
> module purge
> module load pgi/17.3  mvapich2/2.2_pgi_cuda-8.0.44
> 
> cd $PBS_O_WORKDIR
> OPT="MV2_ENABLE_AFFINITY=0 MV2_SHOW_CPU_BINDING=1 MV2_USE_CUDA=1 MV2_USE_GPUDIRECT=1 MV2_NUM_PORTS=2"
> mpirun_rsh -np 1 -hostfile $PBS_NODEFILE $OPT ./a.out
>
> $ qsub submit.sh

1ノード実行時に下記のようなエラーになる。ただし「-mcmodel=medium」オプションを外してコンパイルした実行ファイルは正常終了する。

>[tcag-0003:mpi_rank_0][error_sighandler] Caught error: Segmentation fault (signal 11)
>[tcag-0003:mpispawn_0][readline] Unexpected End-Of-File on file descriptor 6. MPI process died?
>[tcag-0003:mpispawn_0][mtpmi_processops] Error while reading PMI socket. MPI process died?
>[tcag-0003:mpispawn_0][child_handler] MPI process (rank: 0, pid: 17996) terminated with signal 11 -> abort job
>[tcag-0003:mpirun_rsh][process_mpispawn_connection] mpispawn_0 from node tcag-0003 aborted: Error while reading a PMI socket (4)

**Comment by mnakao** [comment]
追記です。
「-mcmodel=medium」オプションを外した状態でも、下記コードはエラー終了します。エラー内容は前スレッドと同じです。

```Fortran
program test
 real(8),allocatable :: A(:,:)[:]
 real(8) :: B(3,5)

 allocate(A(3,5)[*])
 A(:,:) = 0.d0
 B(:,:) = 0.d0
 A(:,1)[1] = B(:,1)
end program test
```

**Comment by hidetoshi-iwashita** [comment]
中尾さん

岩下です。

トランスレータ出力に特におかしいところはなさそうです。
特定環境や特定オプションだけで再現するようなので、
ランタイムの方が可能性があるような気がします。
最初のプログラムでは、allocateが完了する前に代入が始まっているとか、
２つ目のプログラムでは、PUTが終わる前にfinalizeしてしまっているとか、
ないでしょうか。

まず環境変数 XMPF_COARRAY_MSG に 1を設定して実行してみてもらえませんか。＞中尾さん
CAFライブラリの実行ログが出るので、それを送ってください。



On Tue, 18 Jul 2017 08:28:58 +0000 (UTC)
Masahiro Nakao <notifications@github.com> wrote:

> 追記です。
> 「-mcmodel=medium」オプションを外した状態でも、下記コードはエラー終了します。エラー内容は前スレッドと同じです。
> 
> ```Fortran
> program test
>  real(8),allocatable :: A(:,:)[:]
>  real(8) :: B(3,5)
> 
>  allocate(A(3,5)[*])
>  A(:,:) = 0.d0
>  B(:,:) = 0.d0
>  A(:,1)[1] = B(:,1)
> end program test
> ```
> 
> 
> -- 
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub:
> https://github.com/omni-compiler/omni-compiler/issues/179#issuecomment-315995100

岩下
hidetoshi.iwashita@riken.jp

**Comment by mnakao** [comment]
最初のスレッドのメッセージは下記の通りです。
```
CAF[1] Specified Parameters
   runtime message switch        :  on
   pooling/allocation threshold  :  41943040 bytes
   static buffer (localBuf) size :  400000 bytes
   safe buffer mode (PUT only)   :  off
   sync put mode (PUT only)      :  off
   eager communication mode      :  off
   GET-communication interface   :  type 8
   PUT-communication interface   :  type 8
CAF[1] XMPF_COARRAY_MALLOC_POOL_ contains:
  system-defined local buffer :    400000 bytes
  system-defined control data :        32 bytes
  user-defined coarays        :         0 bytes
CAF[1] *** MemoryChunk <0x205bb20 400032 bytes > was made. (400032 bytes)
CAF[1] *** new CoarrayInfo <0x205bc50 (noname)>
CAF[1] *** CoarrayInfo <0x205bc50 (noname)> added to MemoryChunk <0x205bb20 400032 bytes (null)>
CAF[1] *** memory share 400000 bytes from the pool <0x2b79bac86010>
CAF[1] *** new CoarrayInfo <0x205bd10 (noname)>
CAF[1] *** CoarrayInfo <0x205bd10 (noname)> added to MemoryChunk <0x205bb20 400032 bytes '(localBuf)'(null)>
CAF[1] *** memory share 32 bytes from the pool <0x2b79bace7a90>
CAF[1] SYNCALL_AUTO done (count:1, stat=0)
CAF[1] XMPF_COARRAY_PROLOG_ (name='test', rset=0x205bdd0)
CAF[1] XMPF_COARRAY_MALLOC entry
CAF[1] *** MemoryChunk <0x205c120 120 bytes > was made. (120 bytes)
CAF[1] *** new MemoryChunk <0x205c120 120 bytes >
CAF[1] *** MemoryChunk <0x205c120 120 bytes > added to rset=0x205bdd0
CAF[1] *** new CoarrayInfo <0x205c250 (noname)>
CAF[1] *** CoarrayInfo <0x205c250 (noname)> added to MemoryChunk <0x205c120 120 bytes (null)>
CAF[1] SYNCALL_AUTO done (count:2, stat=0)
CAF[1] *** set corank of CoarrayInfo <0x205c250 (noname)>, corank=1
CAF[1] *** set name of CoarrayInfo <0x205c250 'a'>
```
2つ目のスレッドは下記の通りです。
```
CAF[1] Specified Parameters
   runtime message switch        :  on
   pooling/allocation threshold  :  41943040 bytes
   static buffer (localBuf) size :  400000 bytes
   safe buffer mode (PUT only)   :  off
   sync put mode (PUT only)      :  off
   eager communication mode      :  off
   GET-communication interface   :  type 8
   PUT-communication interface   :  type 8
CAF[1] XMPF_COARRAY_MALLOC_POOL_ contains:
  system-defined local buffer :    400000 bytes
  system-defined control data :        32 bytes
  user-defined coarays        :         0 bytes
CAF[1] *** MemoryChunk <0x1f26bd0 400032 bytes > was made. (400032 bytes)
CAF[1] *** new CoarrayInfo <0x1f26d00 (noname)>
CAF[1] *** CoarrayInfo <0x1f26d00 (noname)> added to MemoryChunk <0x1f26bd0 400032 bytes (null)>
CAF[1] *** memory share 400000 bytes from the pool <0x2ad3d2fe6010>
CAF[1] *** new CoarrayInfo <0x1f26dc0 (noname)>
CAF[1] *** CoarrayInfo <0x1f26dc0 (noname)> added to MemoryChunk <0x1f26bd0 400032 bytes '(localBuf)'(null)>
CAF[1] *** memory share 32 bytes from the pool <0x2ad3d3047a90>
CAF[1] SYNCALL_AUTO done (count:1, stat=0)
CAF[1] XMPF_COARRAY_PROLOG_ (name='test', rset=0x1f26e80)
CAF[1] XMPF_COARRAY_MALLOC entry
CAF[1] *** MemoryChunk <0x1f271d0 120 bytes > was made. (120 bytes)
CAF[1] *** new MemoryChunk <0x1f271d0 120 bytes >
CAF[1] *** MemoryChunk <0x1f271d0 120 bytes > added to rset=0x1f26e80
CAF[1] *** new CoarrayInfo <0x1f27300 (noname)>
CAF[1] *** CoarrayInfo <0x1f27300 (noname)> added to MemoryChunk <0x1f271d0 120 bytes (null)>
CAF[1] SYNCALL_AUTO done (count:2, stat=0)
CAF[1] *** set corank of CoarrayInfo <0x1f27300 (noname)>, corank=1
CAF[1] *** set name of CoarrayInfo <0x1f27300 'a'>
```

なお、各行にsync allを挿入しても、同じようにエラーになりました。

**Comment by hidetoshi-iwashita** [comment]
報告者：岩下

経過報告

２例は別件のようです。
共通して言えるのは、どうやらPGIコンパイラのFortran-C間インタフェースが、
これまで経験したコンパイラ（GCC, Intel, Fujitsu, NEC, Hitachi）とかなり違うようで、
それがバグの原因になっています。

後者は目途がつきました。
原因箇所は、可変長引数のCの関数をFortranから呼んでいる部分で、
これを可変長でなくすると通ります。

前者は、Cray pointerと-mcmodel=mediumオプションの組合せの問題のようです。
このオプションによってCray pointerのバイト数が変わるようですが、
これがどこかで不整合を起こしているように見えます。
他のコンパイラでは同じ問題は見つけていません。

以上で一旦調査を止めます。

**Comment by hidetoshi-iwashita** [comment]
報告者：岩下

後者の問題に対応してpush

**Comment by mnakao** [comment]
ありがとうございます。後者の問題が解決していることを確認しました。

**Comment by hidetoshi-iwashita** [comment]
報告者：岩下

原因判明。Cにも同じ問題があるかもしれない。

pgfortranのオプション
    -mcmodel=medium
は2GBを超えるメモリ利用を許すが（デフォルトはsmallで最大2GB）、
同時にオプション
    -Mlarge_arrays
を誘導する。これは１個のオブジェクトが2GBを超えることを許す。
そのため64ビットアドレスが使われる（デフォルトは32ビット）。

ユーザプログラムを-Mlarge_arraysで翻訳し、Omniコンパイラを
デフォルトの-Mnolarge_arraysで翻訳していることになるので、
ライブラリインタフェース部分で不整合が起こっていると考えられる。
試しに
$ xmpf90 -mcmodel=medium -Mnolarge_arrays test.f90
とすると、正常実行された。

対処案１：サポートする
 - トランスレータは各ベンダのオプションを解釈するか独自オプションを
　作って、-Mlarge_arrays相当の指定がある場合とない場合でライブラリ名を
　出し分ける。
 - ランタイムは lib系とlib64系を用意する。

対処案2：すべて制限
 - 32ビット／64ビットはベースコンパイラのデフォルトのみ許す。
 - User's Guide相当（READMEか）に制限事項を書く。
  本インシデントのように誘導されるオプションもあるので、ユーザに分かるように。

**Comment by hidetoshi-iwashita** [comment]
報告者：岩下

開発ミーティングの結果反映

以下のようにドライバとドキュメントで対処する。
 - Omniコンパイラは常に64ビットでビルドする。現在実績のあるコンパイラのうち
  PGI以外はデフォルトが64ビットと思われるので、PGIだけ対処すればよいはず。
 - ユーザプログラムも64ビットでコンパイルする。具体的にはベースコンパイラがPGIのとき
  自動的に -Mlarge_arrays オプションを追加する。
  現在実績のある他のコンパイラでは何もする必要はないはず。
- ドキュメント反映。32ビットにするオプション（-Mnolarge_arrays）は禁止とするか、または
  自動的に無効になるとする。

**Comment by mnakao** [comment]
PGIコンパイラ利用時は、下記のような動作にしました。

- omni compilerのライブラリは -Mlarge_arraysをつけてコンパイルされる（常に64-bit）
- xmpf90/ompf90利用時、-Mlarge_arraysが自動的に追加される
- xmpf90/ompf90利用時、-Mnolarge_arraysがユーザによって追加された場合は、コンパイルエラーとし、その旨をメッセージに出すようにした
- omni compilerは64-bitコンパイラでのみコンパイルされることを、docs/RESTRICTION.mdに追記
