### ISSUE TITLE
Decide ENUMERATOR specification in XcodeML

### ISSUE THREAD

**Issue by shingo-s** [omni-compiler/omni-compiler#222]
New XcodeML tag is required for representing `ENUM`.

Currently, XcodeML specification has only `FenumType` for representing `ENUM` and `ENUMERATOR`.
But it is insufficient to represent where is the `ENUM` construct declared, and it causes the problem for the dependency between declaration statements.

ex)
```fortran
    INTEGER, PARAMETR :: i = 10
    ENUM, BIND(C)
       ENUMERATOR :: a = i
       ENUMERATOR :: b
    END ENUM
    INTEGER, PARAMETER :: j = KIND(b)
```
In the above example, `ENUMERATOR` a depends on `PARAMETER` i and `PARAMETER` j depends on `ENUMERATOR` j.
So the `ENUM` construct should be outputed between the declaration statements of i and j.

To solve this problem, new XcodeML tag `FenumDecl` is required.
```xml
        <varDecl>
          <name>i</name>
          <value>...</value>
        </varDecl>
        <FenumDecl type="type of enum"/>
        <varDecl>
          <name>j</name>
          <value>...</value>
        </varDecl>
```

To try `ENUM`, see a temporary implementation in [feature/branch](https://github.com/omni-compiler/omni-compiler/tree/feature/enumerator).

**Comment by clementval** [comment]
@shingo-s Agree with you

**Comment by h-murai** [comment]
@shingo-s I understand that the situation is the same with FstructType and FstructDecl. So I also agree with you.
