### ISSUE TITLE
Missing 'type' attributes in forallStatement

### ISSUE THREAD

**Issue by shingo-s** [omni-compiler/omni-compiler#242]
When FORALL statement has a type specifiler, F-FrontEnd don't output this type as `type` attribute in `forallStatement`.

```fortran
      FORALL (INTEGER(8) :: i)
        ...
      END FORALL
```
should be translated into
```xml
    <forallStatement type="IXXXXX"> <!-- IXXXXX is type for INTEGER(8) -->
       ....
    </forallStatement>
```

**Comment by h-murai** [comment]
@shingo-s Now the type attribute is output with PR #243. But then no needs for creating the enclosing BLOCK construct or renaming the control variables?

**Comment by shingo-s** [comment]
@h-murai Now BLOCK construct will be remobed if it is not required

**Comment by shingo-s** [comment]
Closed via https://github.com/omni-compiler/omni-compiler/pull/292
