### ISSUE TITLE
TYPE name from external module is not reachable in decompiler

### ISSUE THREAD

**Issue by clementval** [omni-compiler/omni-compiler#276]
```fortran 
MODULE mod1

INTERFACE
  SUBROUTINE gcl_AddFieldToHaloExchange_Wrapper() &
  BIND(c, name='communicationwrapper_add_field_to_halo_exchange')
    USE, INTRINSIC :: iso_c_binding
    TYPE(C_PTR), value    :: field

  END SUBROUTINE gcl_AddFieldToHaloExchange_Wrapper
END INTERFACE

END MODULE mod1
```

When decompiling `TYPE(C_PTR), value    :: field`, `C_PTR` cannot be found as it is not imported or not available for the decompiler. 

the `id` for `C_PTR` should be imported in the XcodeML/F

**Comment by h-murai** [comment]
@shingo-s Is this related to PR #269 ?

**Comment by clementval** [comment]
@h-murai I think it is somehow related but PR #269 does not fix this case.

**Comment by shingo-s** [comment]
@h-murai @clementval #269 does not relate with this issue. Anyway, I'll check it.

**Comment by shingo-s** [comment]
@h-murai @clementval `C_PTR` shoud appear in the `<symbols>` tag in XcodeML. But `FfunctionDecl` doesn't have `<symbols>` tag, so the name resolusion always fails. So this problem occures from XcodeML schema.

I think `FfunctionDecl` should have a `<symbols>` tag.

**Comment by clementval** [comment]
Agreed with @shingo-s

**Comment by clementval** [comment]
@h-murai Can we add this? How is the procedure to fix thw XcodeML specification?

**Comment by h-murai** [comment]
@clementval @shingo-s We'll investigate your proposal about XcodeML and fix it if needed. Please wait for a while.

**Comment by h-murai** [comment]
@clementval We decided to accept your proposal.
@shingo-s Could you modify F_Front and F_Back to add the `<symbols>` section in the `<FfunctionDecl>`?

**Comment by clementval** [comment]
@h-murai thanks!

**Comment by clementval** [comment]
@h-murai @shingo-s PR #281 Would this do the trick?
