### ISSUE TITLE
XMP nodes の生成・削除を繰り返すと Too many communicators error

### ISSUE THREAD

**Issue by atabuchi** [omni-compiler/omni-compiler#278]
XMP nodes の生成・削除を繰り返すとMPI_Comm_dup() において Too many communicators error が起きる。

コード
```c
int main(void)
{
    int i;

    for(i = 0; i < 10000; i++){
        printf("iter = %d\n", i);
#pragma xmp nodes p(*)
    }

    return 0;
}
```

実行環境
HA-PACS/TCA, Intel 17.0.2, IntelMPI 2017.2

実行結果
```
iter = 0
iter = 1
...skip...
iter = 8185
iter = 8186
Fatal error in PMPI_Comm_dup: Other MPI error, error stack:
PMPI_Comm_dup(192)..................: MPI_Comm_dup(MPI_COMM_SELF, new_comm=0xac1c04) failed
PMPI_Comm_dup(171)..................: fail failed
MPIR_Comm_dup_impl(57)..............: fail failed
MPIR_Comm_copy(845).................: fail failed
MPIR_Get_contextid_sparse_group(676): Too many communicators (0/16384 free on this process; ignore_id=0)
```

1つの nodes に対して 2つの communicator が適切に解放されていないようである。

**Comment by h-murai** [comment]
@atabuchi 私の知る限り、そもそも、MPIの制限により、生成できるコミュニケータの個数には限界があります。その上で、「2つの communicator が適切に解放されていない」というのはどういうことですか？

**Comment by atabuchi** [comment]
@h-murai 
エラーメッセージを見るとコミュニケータは 16384 個まで生成でき、イテレーションがその約半分まで回っているので、1つのnodesの生成・削除ごとに2個のコミュニケータが解放されずに残っていると思いました。

また、xmp_nodes.c, xmp_nodes_stack.c あたりでpritnfデバッグしてみたのですが、nodes生成時には3回 MPI_Comm_dup() が呼ばれているのに対し、削除時には MPI_Comm_free() は1度しか呼ばれていませんでした。
xmp_nodes.c: create_subcomm() の呼び出しで生成したコミュニケータが解放されていないようです。

**Comment by mnakao** [comment]
そのあたりは私が作成したので直します。
申し訳ありませんが、来週までお待ち下さい。
