### ISSUE TITLE
Calling external function causes segumentation fault

### ISSUE THREAD

**Issue by shingo-s** [omni-compiler/omni-compiler#298]
Calling external function causes segmentation fault

For example:
```fortran
      SUBROUTINE sub(f)
        implicit none
        integer :: f
        integer :: a
        a = f()
      END
```

It seems that 69edf0dd3 causes this regression.

**Comment by clementval** [comment]
@shingo-s Sorry for this, I'll have a look

**Comment by h-murai** [comment]
solved along with another issue.
