### ISSUE TITLE
RESULT does not work with TYPE statement

### ISSUE THREAD

**Issue by shingo-s** [omni-compiler/omni-compiler#361]
If the function with `RESULT` has a `TYPE` statement, `F_Front` adds a variable named the function name.

```fortran
      FUNCTION f() RESULT(r)
        LOGICAL :: r
        TYPE t
          INTEGER :: v
        END TYPE t
      END FUNCTION f
```

The above code will be translated into:

```fortran
FUNCTION f ( ) RESULT(r)
 use xmpf_coarray_decl
 LOGICAL :: f = r
 TYPE :: t
  INTEGER :: v
 END TYPE t
 LOGICAL :: r
END FUNCTION f
```

**Comment by h-murai** [comment]
Note: 2d475cb is just a partial resolution.  To resolve this issue completely, it's needed to implement `is_id_used_in_struct_member` in `F-output-xcodeml.c`.
