### ISSUE TITLE
Calling a dummy procedure causes a segmentation fault.

### ISSUE THREAD

**Issue by shingo-s** [omni-compiler/omni-compiler#380]
Once the identifier is used as a argument, it can not be used as a function.

ex)
```fortran
       SUBROUTINE s(f)
         INTEGER :: f
         INTEGER :: v
         CALL g(f)
         v = f()                        ! F_Front shows an error "identifier 'f' is used as a function"
       END SUBROUTINE s

       SUBROUTINE g(f)
         INTEGER :: f
         PRINT *, f()
       END SUBROUTINE g

       END
```

**Comment by h-murai** [comment]
First of all, according to the specification, an dummy procedure shall have an EXTERNAL attribute to be used as an actual argument. So, the above is a wrong Fortran program. Actually, if we added the EXTERNAL attribute to `f`, F_Front could accept it.

On the other hand, if we remove the CALL statement in the code, it causes a segmentation fault.

```fortran
       SUBROUTINE s(f)
         INTEGER :: f
         INTEGER :: v
         v = f()
       END SUBROUTINE s
```

**Comment by h-murai** [comment]
The segmentation fault reported in the above comment has been fixed along with some updates.
