### ISSUE TITLE
[REGRESSION]:  <function_name> is a function, not a subroutine

### ISSUE THREAD

**Issue by clementval** [omni-compiler/omni-compiler#445]
With recent change, a subroutine is detected as a function but this is actually a subroutine. 

I'll provide a minial example code today.

**Comment by shingo-s** [comment]
@clementval 

Thanks to your report. 'llI fix it in https://github.com/omni-compiler/omni-compiler/pull/446

**Comment by clementval** [comment]
@shingo-s I still have the problem. I'll try to give you a minimal example. The file I have now is more than 2000 lines of code so I'm trying to reduce the example and the dependencies.

**Comment by clementval** [comment]
Fixed by #465
