### ISSUE TITLE
stdlib.hをインクルードするとエラー

### ISSUE THREAD

**Issue by mnakao** [omni-compiler/omni-compiler#46]
@a-wada-rk 

環境
- gcc-4.9.2
- openmpi-1.8.4
- java-1.7.0_101

XMP/Cにおいてstdlib.hをインクルードするファイルをコンパイルすると、エラーになります。-O2が必要です。
> $  cat a.c
> #include \<stdlib.h\>
> 
> $ xmpcc -O2 -c a.c
> fatal: cannot convert Xcode to XcodeML.
> Xcode = (FUNCTION_CALL:int (POINTER_REF:P127 (VAR:P127 __compar)) (LIST (VAR:P134 __key) (VAR:P136 __p)))
> ・・・

2016年9月14日13時10分のpushからこのエラーが発生しています。
ハッシュタグd0f633cはこのエラーは出ませんが、de6586c6以降は上記のエラーになります。

**Comment by mnakao** [comment]
追記です。
ハッシュタグe5fe84とa0a96aの間の、
XcodeML-Exc-Tools/src/exc/xcodeml/XmcXobjectToXcodeTranslator.javaが問題のようです。

ただし、自分のマシン（Debian 8.6）ではこのエラーは出るのですが、ソフトウェア環境を同じにしたテスト環境（omni-compiler.org）のCentOS 7.2.1511ではエラーは出ませんでした。

**Comment by mnakao** [comment]
Debianで利用されているstdlib.hや、それからさらにインクルードしているヘッダファイルがCentOSと異なるようです。テストに必要な一式を添付します。このテストを用いると、CentOSでも同様の問題が発生しました。

[test.zip](https://github.com/omni-compiler/omni-compiler/files/498319/test.zip)

**Comment by a-wada-rk** [comment]
97026542da5fc4d2e415f8698389297c1f8f79d9
にて修正しました。ご確認をお願いいたします。

**Comment by mnakao** [comment]
修正確認しました。
