### ISSUE TITLE
Ability to keep comment in the XcodeML and in generated code

### ISSUE THREAD

**Issue by clementval** [omni-compiler/omni-compiler#485]
I remember we talked about this feature a while ago. 

```bash
F_Front -fleave-comment
```

Is this feature totally abandoned? Is there an interest on your side to revive this feature? 
Any idea of the workload to do it? I have some kind of interest for this so I would be glad to do/help for it

**Comment by h-murai** [comment]
@clementval Now we are focusing the support of Fortran 2008, and give the comment feature a low priority. However, our effort for Fortran 2008 is almost finished and I think we'll be able to touch the feature soon.

**Comment by clementval** [comment]
@h-murai Thanks for the information. No need to rush for this. It was just to know if it was still in the pipeline. I'm happy to hear that it is the case.

**Comment by h-murai** [comment]
@clementval I'm considering that it's possible to keep "comment lines" but it's very difficult or impossible to keep a comment that follows a Fortran statement, as follows.

```fortran
integer k  ! comment after a declaration
```

What do you think about this?

**Comment by clementval** [comment]
@h-murai Yeah I think it make sense. Supporting all would be to complicated I think and there is porbably other priority than this. So I totally agree with you.

**Comment by h-murai** [comment]
@clementval Now, comment lines that begin with `!` are kept in XcodeML and the generated source code if you specify the `-fleave-comment` option. Please try it.

**Comment by clementval** [comment]
@h-murai Looks like to work great! Thanks!
