### ISSUE TITLE
CHARACTER LENGH in the array constructor can accept a variable

### ISSUE THREAD

**Issue by shingo-s** [omni-compiler/omni-compiler#494]
The following code is valid.

```fortran
      INTEGER :: i = 10
      PRINT *, [CHARACTER(i)::]
      END
```

**Comment by h-murai** [comment]
@shingo-s It looks to me that the latest F_Front bbdad1370c7df2b76848a8553e847f45e81aa33b accepts the above code.

**Comment by shingo-s** [comment]
bbdad1370c7df2b76848a8553e847f45e81aa33b solves this issue becauses it contains some commits from https://github.com/omni-compiler/omni-compiler/pull/522 for this issue. Maybe I missplaced it.

This branch also contains the modification for the problem came from those commits.
The problem is F_Front accepts the following invalid code.

```fortran
      INTEGER :: i = 10
      CHARACTER(i) :: c ! should be fail
      END
```
