### ISSUE TITLE
Using implicit external procedure as an argument causes error

### ISSUE THREAD

**Issue by shingo-s** [omni-compiler/omni-compiler#508]
`F_Front` fails with the following code.

```fortran
      INTEGER :: i
      INTEGER :: d
      CALL sub(d) ! If this line does not exsit, F_Front works
      i = d()
      END
```

**Comment by h-murai** [comment]
@shingo-s To use an external procedure as an actual argument, you have to explicitly declare the EXTERNAL attribute with the procedure. (In other words, a compiler can assume that an identifier without the EXTERNAL attribute that appears as an actual argument is not a procedure but a variable.) So the above is a wrong Fortran program.
