### ISSUE TITLE
xmp_mallocを用いた分散配列の動的確保と静的確保の組合せに対する不具合

### ISSUE THREAD

**Issue by mnakao** [omni-compiler/omni-compiler#516]
@h-murai @atabuchi 

下記のコードでエラーになります。
```C
#include <xmp.h>

int a[10];
#pragma xmp nodes p[1]
#pragma xmp template t1[10]
#pragma xmp distribute t1[block] onto p

int main(int argc, char** argv){
#pragma xmp align a[i] with t1[i]

  int *b;
#pragma xmp template t2[:]
#pragma xmp distribute t2[block] onto p
#pragma xmp align b[i] with t2[i]
#pragma xmp template_fix[block] t2[10]
  b = xmp_malloc(xmp_desc_of(b), 10);

  return 0;
}
```

> % xmpcc remap.c
> % mpirun -np 1 ./a.out
> [RANK:0] XcalableMP runtime error: _XMP_coarary_detach: poped coarray desc is not the same to argument

原因は、a[]を確保してからb[]を確保しているのにも関わらず、下記の中間コードのように、先に配列aのdeallocが実行されてしまうことです。

```C
static int xmpc_main(int argc, char * * argv)
{
int * _XMP_ADDR_a;
void * _XMP_DESC_a;
  :
_XMP_alloc_array((void **)&_XMP_ADDR_a, _XMP_DESC_a, ... );
  :
b = (xmp_malloc(_XMP_desc_of(_XMP_DESC_b), 10));
  :
_XMP_dealloc_array(_XMP_DESC_a);
_XMP_finalize_array_desc(_XMP_DESC_a);
  :
_XMP_finalize_array_desc(_XMP_DESC_b);
  :
}
```
順番的に、bを開放してから、aを開放すればOKです。

**Comment by atabuchi** [comment]
@mnakao @h-murai 

XcodeML-Exc-Tools/src/exc/xcalablemp/XMPlocalDecl.java の 240行目付近を修正して正しい順序にするのが良いかと思います。

エラーの原因となっている _XMP_coarray_detach() ですが、分散配列の gmove 用 coarray を detach する際に、ランタイムが管理している coarray stack から pop したものと違うために出ています。
coarray を attach する際にはそもそも内部の coarray stack で管理しないようにしてもおそらく問題ない気がします。

**Comment by mnakao** [comment]
@atabuchi 
ありがとうございます。直しました。
