### ISSUE TITLE
GNU Extension intrinsic

### ISSUE THREAD

**Issue by clementval** [omni-compiler/omni-compiler#555]
Would it be useful to have a mode where GNU extension intrinsic are allowed in `F_Front`?

@h-murai @shingo-s What do you think about it?

**Comment by h-murai** [comment]
@clementval @shingo-s I think it's useful. Actually, `C_Front` has already supported a part of GNU extensions, and I've been considering that `F_Front` should also do.

**Comment by clementval** [comment]
@h-murai Ok, nice. I'll try to set up something and make a PR when it's ready.

**Comment by clementval** [comment]
Closed by #556
