### ISSUE TITLE
configure check --target option and now fails. 

### ISSUE THREAD

**Issue by clementval** [omni-compiler/omni-compiler#558]
@h-murai Why the configure script is now checking the target? It was working fine on macos so far and now it fails because of this check... 

Can we add it to the list? 

```bash
configure: error: --target=x86_64-apple-darwin17.4.0 is not supported
```

This has come with commit d15954d860861cbe6dac61706bf1ec93d8ceffe4

**Comment by mnakao** [comment]
@clementval 
Sorry for bothering you.
These lines were added due to my misunderstanding.
I removed these.

Thanks,

**Comment by clementval** [comment]
@mnakao No worries and thanks a lot for the quick fix!
