### ISSUE TITLE
xcodeml-tools cannot be built without libxmpf directory

### ISSUE THREAD

**Issue by hidetoshi-iwashita** [omni-compiler/omni-compiler#581]
報告者：岩下

omni-compiler/xcodeml-tools をgit cloneしてビルドするとき、libxmpfディレクトリを
参照している。このディレクトリがないと、ビルドが失敗する。

**Comment by hidetoshi-iwashita** [comment]
報告者：岩下

調査

coarrayトランスレータが生成する手続き名（総称名）について、
F_Backendが勝手にexternal宣言を付けてしまいます。
手続き名はF_Backendで生成されるuse文で参照されるモジュールの
中で定義されているので、external宣言と重なるとコンパイルエラーに
なります。
これを回避するために手続き名のリストをF_Backendが知る必要があり、
make時にリストを生成するためにlibxmpfを見に行っていました。

F_Backendは、手続き名にexernal属性が付いていない場合でも、
自分で判断して必要と思ったらexternal属性を付けてしまいます。
本来は、XcodeMLに表現されていない属性を勝手に付け加えるべきでは
ないと思いますが、そうしたい理由があったのだと思います。

正攻法では、
- 手続き名のexternal属性をF_Backendで勝手に付け加えないようにするか、
　または、externalではないことを宣言する新しい属性 nonexternal（Fortranには
　ない）をXcodeMLに追加する。
または
- モジュールをommi-compilerのパスの途中で生成できる仕組みを作る。
などが必要になり大がかりです。

現実的な解決策としては、手続き名のリストもXmOptionを使って伝えるしかない
かなあと思っています。

**Comment by mitsuhisa-sato** [comment]
Attribute を使うべきだと思います。

-- M. Sato

2018/05/25 16:43、Hidetoshi Iwashita <notifications@github.com>のメール:

**Comment by hidetoshi-iwashita** [comment]
6/12頃に以下のように実装

- coarrayのパス中で、external宣言を抑止すべき手続き名のリストをXmOptionの中に生成。

- F-Backendでは、external宣言を自動付加するときに、このリスト中の名前は対象外とする。

libxmpf/src/xmpf_coarray_decl.F90　で定義されているモジュールに、
coarrayのランタイムのインタフェースが宣言されている。
ここで定義されている名前が、external宣言抑止の対象。
F-Backendでは、このモジュールに対するuse文が生成される。
