### ISSUE TITLE
FX10 : SIGBUS, tests/xcalablemp/local-view/coarray/F/SCOPE/sakagami460-2.x

### ISSUE THREAD

**Issue by a-wada-rk** [omni-compiler/omni-compiler#6]
実行環境
-   FX10
-   frt V1.2.1
-   omnicompiler-20160621 (最新)

現象
```
>> export XMP_ONESIDED_HEAP_SIZE=70M; mpirun -np 3 ./sakagami460-2.x
jwe0019i-u The program was terminated abnormally with signal number SIGBUS.
           signal identifier = BUS_ADRALN, invalid address alignment
 error occurs at xmpf_main_                      line 23 loc 0000000000103248 offset 0000000000000188
 xmpf_main_                          at loc 00000000001030c0 called from loc 0000000000103a0c in MAIN__       line 15
```

初期調査
"-O1" で再現せず、"-O2"  で再現。後者では翻訳時のメッセージに、
```
  jwd8208o-i  "sakagami460-2.f90", line 23: Method of calculating sum or product is changed.
```
と出力される点が異なっている。a が coarray である。
```
 22 enddo
 23 b=sum(a)
 24 syncall
```
の部分を、
```
 22 enddo
 23 b=0.0
 24 do j=1,ly
 25    do i=1,lx
 26      b=b+a(i,j)
 27    enddo
 28 enddo
 29 syncall
```
とすると再現しない。K(V1.2.0) では当該最適化が行われず再現しない。

**Comment by hidetoshi-iwashita** [comment]
frt 1.2.1の不具合と思われる．
組込み関数sumの引数配列aは8バイトrealだが，4バイトrealのスカラ変数bの直後に
allocateされているため，8バイト境界に割付けられていない．
現象としてSIGBUSが発生している．
aを8バイト境界にすると正常に動作することを確認した．

対処として以下の2点
- ランタイムライブラリは8バイト変数がcoarray宣言されているとき，8バイト境界から割付けるように
  修正すべき．これはfrtの不具合に関わらず，性能のため．
- frtの不具合はもう少し調査し対応を検討．cray pointerを介してallocateした領域に限った問題なら
  特に重大な問題ではない．

**Comment by hidetoshi-iwashita** [comment]
修正完了しFX10で確認．
