### ISSUE TITLE
[C]loop指示文における構造体利用時のエラー

### ISSUE THREAD

**Issue by mnakao** [omni-compiler/omni-compiler#601]
@h-murai 

下記のコードでエラーになります。
```
#pragma xmp template t(0:3)
#pragma xmp nodes p(1)
#pragma xmp distribute t(block) onto p

typedef struct QCDSpinor {
  double v[100];
} QCDSpinor_t;

static void norm2_t(QCDSpinor_t w[4])
{
#pragma xmp align w[j] with t(j)
  int tmp;

#pragma xmp loop (i) on t(i)
  for(int i=0;i<4;i++){
    for(int j=0;j<100;j++)
      tmp = w[i].v[j];
  }
}
```

> % xmpcc main.c -c
> Exception in thread "main" java.lang.UnsupportedOperationException: (MEMBER_ARRAY_REF:A0 (ADDR_OF:P2 (ARRAY_REF:S0 (ARRAY_ADDR:A1 w, param) (LIST:S0 (VAR:int i, local)))) (IDENT v, null))
> 	at exc.object.Xobject.getSym(Xobject.java:266)
> 	at exc.xcalablemp.XMPrewriteExpr.rewriteLoopIndexInLoop(XMPrewriteExpr.java:2130)
> 	at exc.xcalablemp.XMPtranslateLocalPragma.callLoopSchedFuncTemplate(XMPtranslateLocalPragma.java:1802)
> 	at exc.xcalablemp.XMPtranslateLocalPragma.scheduleLoop(XMPtranslateLocalPragma.java:1571)
> 	at exc.xcalablemp.XMPtranslateLocalPragma.translateMultipleLoop(XMPtranslateLocalPragma.java:1293)
> 	at exc.xcalablemp.XMPtranslateLocalPragma.translateLoop(XMPtranslateLocalPragma.java:836)
> 	at exc.xcalablemp.XMPtranslateLocalPragma.translatePragma(XMPtranslateLocalPragma.java:89)
> 	at exc.xcalablemp.XMPtranslateLocalPragma.translate(XMPtranslateLocalPragma.java:47)
> 	at exc.xcalablemp.XMPtranslate.translate(XMPtranslate.java:65)
> 	at exc.xcalablemp.XMPtranslate.doDef(XMPtranslate.java:36)
> 	at exc.object.XobjectDefEnv.iterateDef(XobjectDefEnv.java:90)
> 	at exc.util.omompx.main(omompx.java:333)

下記のコミットからのエラーです。
> commit 07c7b1c8e37e27e7c543e1a449093a02a89afe28
> Merge: f6fc48866 2cb424d7d
> Author: Hitoshi Murai <h-murai@riken.jp>
> Date:   Thu Apr 19 11:09:14 2018 +0900
> 
>     Merge branch 'master' into keep_array

**Comment by h-murai** [comment]
@mnakao 

最新版では、`XMPutil.getArrayName`内の以下の箇所でエラーになっています。

```java
	String structName = arrayAddr.getArg(0).getArg(0).getSym();
```
これは、例えば`w[i].v`のような、構造体変数(`.`の前の部分)が配列である場合に対応していないためです。

そのような場合に対応するとして、上の行の少し下にある以下の行では、

```java
	return XMP.STRUCT + structName + "_" + arrayName;
```

(おそらく分散されたメンバを扱うために)ダミーの配列名が返されていますが、構造体変数が配列である場合にはどのような名前を返しておけばいいですか？

**Comment by mnakao** [comment]
@h-murai 
最新版でテストし忘れていました。すみません。

それで、最初のエラーの原因は、xcodeml-toolsのようでした。
git diff 6e5f91c 12b7a60を参照ください。

```
-    if (s_arrayToPointer || EXPR_CODE(tmp_aryRef) != EC_IDENT ||
+    if (!s_useXMP && (s_arrayToPointer || EXPR_CODE(tmp_aryRef) != EC_IDENT ||
```
"!s_useXMP &&"をコメントアウトすると、正常に動作しました。

**Comment by h-murai** [comment]
@mnakao そうなのですが、そのバグの上に、構造体メンバを分散する機能が実装されているので、全部まとめて修正します。そこで、「構造体変数が配列である場合にはどのような名前を返しておけばいいですか？」という質問になります。

**Comment by mnakao** [comment]
構造体変数が分散配列の場合（構造体変数のメンバが分散されていない場合）は、以前と変更していないです。

なので、下記のコードは、
```
#pragma xmp nodes p[2]
#pragma xmp template t[10]
#pragma xmp distribute t[block] onto p
struct st{
  int array;
};
struct st st_val[10];
#pragma xmp align st_val[i] with t[i]

int main(){
  #pragma xmp loop on t[i]
    for(int i=0;i<10;i++)
      st_val[i].array = 0;
}
```
下記のようになります。
```
struct st * _XMP_ADDR_st_val;
static void * _XMP_DESC_st_val;

for(i = (0); i < (5); i += (1))
  ((_XMP_M_GET_ADDR_E_1(_XMP_ADDR_st_val, i))->array) = (0);
```

**Comment by h-murai** [comment]
@mnakao 構造体変数が配列である場合、以下のコードはどうあるべきですか？

```java
return XMP.STRUCT + structName + "_" + arrayName;
```

**Comment by mnakao** [comment]
構造体変数名を返してほしいので、
```C
return XMP.STRUCT;
```
になります。
