### ISSUE TITLE
[F]Coarrayとallocatedの組合せのエラー

### ISSUE THREAD

**Issue by mnakao** [omni-compiler/omni-compiler#618]
テストの「allodeallo.f90」、「decl3.f90」、「allo1.f90」、「allo3.f90」で結果不正が出ています。原因は同じと思います。

上のコードでは、下記のようなパターンがあります。
```Fortran
real, allocatable :: a(:)[:]
if (allocated(a)) then
```
このコードは下記のようにトランスレーションされます。
```Fortran
REAL , POINTER :: a ( : )
IF ( associated ( a ) ) THEN
```

ここで、allocated()がassociated()に変化しています。associated()には未定義のポインタは指定できません。そのため、associated(a)の返ってくる値は、gccのバージョンによって異なります。gcc-4.8.5では常にFALSEを返しますが、gcc-8.3.0ではFALSEの場合とTRUEの場合があります。

直し方としては、下記のようにnullify関数を使って、明示的に空状態のポインタであることを指定してやればいいかと思います。

```Fortran
REAL , POINTER :: a ( : )
nullify(a)
IF ( associated ( a ) ) THEN
```

**Comment by mnakao** [comment]
@h-murai 
nullify関数を使わなくても、下記のようにnull()で処理化することで、このバグは解決できると思うのですが、トランスレータのどの箇所を変更すればよいのかわかりませんでした。ご指示いただけませんでしょうか。

```Fortran
REAL , POINTER :: a ( : ) => null()
IF ( associated ( a ) ) THEN
```

**Comment by h-murai** [comment]
例えば、`BlockList.declLocalIdent`を使えばできます。

**Comment by mnakao** [comment]
@h-murai 

Fixできたと思うのですが、Fortranは自信がないので確認していただけないでしょうか。
テストはすべて通っています。

xmpF/XMPcoarray.javaの

```C
  public void setPointer() {
    ident.Type().setIsFpointer(true);
}
```

を下記のように変更しました。
```C
  public void setPointer() {
    ident.Type().setIsFpointer(true);

    if(ident.getStorageClass() == StorageClass.FLOCAL){
      Ident nullId = declIntIntrinsicIdent("null()");
      BlockList blist = fblock.getBody();
      Xobject x = blist.findLocalDecl(name);
      x.setArg(1, Xcons.functionCall(nullId, null));
    }
  }
```

StorageClassで場合分けしているのは、サブルーチン内や関数内ではnull()による初期化は不要だからです。

**Comment by h-murai** [comment]
- `null()`の()は不要では？
- `if(ident.getStorageClass() == StorageClass.FLOCAL)`だと、サブルーチン内や関数内だけ初期化していることになりませんか？
- 組込み関数nullの返り値はたぶんintegerではないですが、便宜上ということですね。

**Comment by mnakao** [comment]
- ()がないと、''REAL , POINTER :: a ( : ) => null''のようになってしまうのです。
- if(ident.getStorageClass() != StorageClass.FPARAM)でどうでしょうか。
- はい。便宜上です。

**Comment by h-murai** [comment]
`Xcons.functionCall(nullId, null))`を、`nullId.Call(null)`か、`Xcons.functionCall(nullId, Xcons.List()))`にしたらどうでしょうか？
FPARAMはそれでいいと思います。

**Comment by mnakao** [comment]
- nullId.Call(null)にすると、''REAL , POINTER :: a ( : ) => null'になり、コンパイルエラーになります。
- Xcons.functionCall(nullId, Xcons.List())にすると、トランスレーション時に下記のようなエラーになります。
```
fatal: cannot convert Xcode to XcodeML.
Xcode = (LIST)
```

**Comment by h-murai** [comment]
うーん、下のコードをF_Front -> F_Backとすると、正しく変換されます。`nullId.Call(null)`とした場合に生成されるXcodeMLはどうなっていますか？ つまり、下に挙げたXcodeMLと同じなら問題ないはずなので、どこかが違っているはず。

```
$ cat foo.f90
program test
  real, pointer :: a(:) => null()
end program test
$ F_Front foo.f90
...
        <varDecl lineno="2" file="foo.f90">
          <name type="A55e4b6d2b1a0">a</name>
          <value>
            <functionCall type="V55e4b6d2b5d0" is_intrinsic="true">
              <name>null</name>
            </functionCall>
          </value>
        </varDecl>
```

**Comment by mnakao** [comment]
nullId.Call(null)とした場合は、下記のようになります。
```
<varDecl file="allo1.f90" lineno="2">
  <name type="A55e3bcac2430">a</name>
  <value>
    <Ffunction type="FXc">null</Ffunction>
  </value>
</varDecl>
```

また、少し前のスレッドで書いた下記のトランスレーションのコードの場合、
```
Ident nullId = declIntIntrinsicIdent("null()");
BlockList blist = fblock.getBody();
Xobject x = blist.findLocalDecl(name);
x.setArg(1, Xcons.functionCall(nullId, null));
```
は、下記のようになります。
```
<varDecl file="allo1.f90" lineno="2">
  <name type="A55fafc3bc430">a</name><value>
  <Ffunction type="FXc">null()</Ffunction>
</value>
</varDecl>
```

どちらにせよ、functionCallのタグでなく、Ffunctionのタグになっています。
類似コードを調べて、適用させているのですが、うまくいかないです。

**Comment by h-murai** [comment]
@mnakao ブランチfunction_in_declで対処してみましたので、試してもらえませんか？

**Comment by mnakao** [comment]
@h-murai ありがとうございます。28ce67bで直ったことを確認しました。
