### ISSUE TITLE
xmpf_coarray_allocated_bytes()の不具合

### ISSUE THREAD

**Issue by mnakao** [omni-compiler/omni-compiler#622]
tests/XMP/local-view/coarray/F/STRUCT/alloc0.f90 が結果不正です。原因は関数xmpf_coarray_allocated_bytes()です。

このエラーはgccのバージョンに依存します。v4.8.5ではエラーになりませんが、v8.3.0ではエラーになります。

alloc0.f90を参考に、エラーの発生する最小コードを下記に示します。
```Fortran
program aa
  type g0
     integer*8 a(10)
  end type g0

  type g1
     integer*8 a(10)
     type(g0), pointer :: p(:)
  end type g1

  type(g1) :: s1, cs1[*]

  if (xmpf_coarray_allocated_bytes() < sizeof(s1)) then
     write(*,*) "Error !"
  endif
  write(*,*) xmpf_coarray_allocated_bytes(),    sizeof(s1)
end program aa
```

なお、構造体g1の中の`` type(g0), pointer :: p(:)``をコメントアウトすると、エラーは発生しません。

**Comment by mnakao** [comment]
@h-murai このバグの原因はXMPcoarray.javaの関数_getPointerComponentLength_atmost()が原因でした。その関数のコメントに詳しく書いてあるのですが、例えば、ポインタ型のp(:)があるとすると、gfortran-4.8.5では、そのサイズは48です。しかし、gfortran-8.3.0では64です。つまり、固定値が使われています。
どうすれば良いでしょうか？
最新のgfortranに合わせるのも手と思いますが。

**Comment by h-murai** [comment]
ポインタ型の構造体成分のサイズは、実装依存ですよね。つまり、gfortranのバージョン違いに限らず、コンパイラの種類ごとの対応が必要ということになります。根本的な解決は非常に難しそうですが、特に以下の３種類に関して対応することは可能ですか？ (configureで切り分ける)

- `p(:)`のサイズが48のgfortran (バージョンXXX以前)
- `p(:)`のサイズが64のgfortran (バージョンXXX以降)
- 富岳

あと、`sizeof`ってFortranの標準ではないようですが、富岳(富士通コンパイラ)でも動いたのですね。

**Comment by mnakao** [comment]
@h-murai 了解しました。
なお、ちょっと調べてみると、 p,  p(:),  p(:,:), p(:,:,:) の各コンパイラにおけるそれぞれの値は、
- gfortran-4.8.5：8, 48, 72, 96
- gfortran-8.3.0：8, 64, 88, 112
- 富岳：16, 56, 88, 120

で、結構、バラバラでした。
