### ISSUE TITLE
Network Error Using Open MPI 4.0.5 backend and TCP

### ISSUE THREAD

**Issue by bkmgit** [omni-compiler/omni-compiler#626]
Get the following error when using Omni Compiler with GCC 9 compilers, OpenMPI 4.0.5 on Cent OS 8 on a 2 node "cluster" using TCP when running the STREAM-dynamic example on 2 processes (program runs fine on 1 process without external communication):

```
mpirun -np 2 --hostfile hostfile  --mca orte_base_help_aggregate 0 STREAM-dynamic 32768 
--------------------------------------------------------------------------
WARNING: Open MPI failed to TCP connect to a peer MPI process.  This
should not happen.

Your Open MPI job may now hang or fail.

  Local host: centos-1cpu-1gb-es-mad1
  PID:        272589
  Message:    connect() to 10.7.0.188:1024 failed
  Error:      Operation now in progress (115)
--------------------------------------------------------------------------
--------------------------------------------------------------------------
WARNING: Open MPI failed to TCP connect to a peer MPI process.  This
should not happen.

Your Open MPI job may now hang or fail.

  Local host: centos-1cpu-1gb-es-mad2
  PID:        292546
  Message:    connect() to 10.7.0.187:1024 failed
  Error:      Operation now in progress (115)
--------------------------------------------------------------------------
```

The hostfile contains only the ip addresses 10.1.0.2 and 10.1.0.3 for which `mpirun -np 2 --hostfile hostfile hostname` works, as do other regular MPI programs. Any suggestions on the cause of the error would be helpful.

**Comment by mnakao** [comment]
On my environment (Debian 10.2, gcc-8.3.0, Openmpi-4.0.5),  STREAM-dynamic can be run.
Looking at your message, it looks like it is trying to connect to 10.7.0.187 and 10.7.0.188.
Is the hostfile correct?

**Comment by bkmgit** [comment]
The hostfile is correct. The micro cluster is in a public cloud, so I expect it is a problem of interaction between several software pieces that would not typically be used in standard HPC.  The software runs correctly on a single node. Does your setup on Debian have multiple nodes?  Is Firewalld running?

I will try MPICH and GASNET as well.

**Comment by mnakao** [comment]
My cluster has some nodes, and I confirm the XMP program runs on some nodes.
My Debian cluster does not use firewall.

In fact, Omni Compiler translates an XMP code to an MPI code, and compile it by mpicc command internally.
Thus, if your environment supports MPI programs, XMP programs can be run.

Did an MPI program work on your environment ?

**Comment by bkmgit** [comment]
Yes MPI programs run - have only tried a few though, calculate Pi, Hello World. Will need to see which MPI functions are being used. Both STREAM and Hello World  XMP versions give similar errors though.

**Comment by mnakao** [comment]
Thank you for your reply.
Umm, an XMP application is equivalent to a regular MPI application unless you are using GASNet.
I'm sorry, I don't know the cause of the error.

**Comment by bkmgit** [comment]
It seems to work with MPICH 3.3.2

Does XMP modify how OpenMPI creates TCP connections?

**Comment by mnakao** [comment]
Good news !!

> Does XMP modify how OpenMPI creates TCP connections?
No. XMP uses only normal MPI functions for communication.

**Comment by bkmgit** [comment]
After reading through section 7.2 [here](https://www.open-mpi.org/faq/?category=tcp#tcp-multi-network) could get it to work, need to specify network interface to use as in the cloud many network interfaces can be created. For some reason OpenMPI is more aggressive when running XMP programs than when running regular MPI programs.

mpirun -np 2 -hostfile ./hostfile --mca btl_tcp_if_include eth3  ./C_hello                             
node num = 0, Hello World
node num = 1, Hello World

 mpirun -np 2 -hostfile ./hostfile --mca btl_tcp_if_include eth3  ./STREAM-dynamic 32768 
[Vector size is 32768] Total Triad 36.8851 GB/s on 2 nodes
Number of Threads requested = 1
Solution Validates
