### ISSUE TITLE
selected_real_kind triggers a segmentation fault

### ISSUE THREAD

**Issue by clementval** [omni-compiler/omni-compiler#65]
If the intrinsic function `selected_real_kind` is used from a module, a segmentation fault occurs during the type declaration compilation.

file: mo_kind.f90
```
module mo_kind
  integer, parameter :: r4 = selected_real_kind(6, 37)
end module mo_kind
```

file: mo_module.f90
```
module mo_module
  implicit none
  contains
  subroutine sub1()
    use mo_kind, only : r4
    real(kind=r4) :: t
  end subroutine sub1
end module mo_module
```

Then if we use `F_Front`
```bash
F_Front mo_kind.f90
F_Front mo_module.f90
Segmentation fault: 11
```

The problem is in `expv_reduce_kind` in the file `F-compile-decl.c` the `find_ident` returns `NULL`. 

Any idea why the ident is not found? I can fix the problem if you have an hint where to start. 

@mnakao @h-murai @shingo-s do you have any idea?

**Comment by clementval** [comment]
Related to #108

**Comment by mitsuhisa-sato** [comment]
fixed.

**Comment by mitsuhisa-sato** [comment]
Valentine, could you check and close this?

**Comment by clementval** [comment]
@mitsuhisa-sato The fix is fine! Thanks a lot!
