### ISSUE TITLE
F_Front: Segmentation fault with function call's name

### ISSUE THREAD

**Issue by clementval** [omni-compiler/omni-compiler#8]
I had several issue with segmentation fault occurring with F_Front. 

The problem happens from time to time when trying to parse program with function call in expression. Like this test `test/testdata/contains.f90`. 
https://github.com/omni-compiler/omni-compiler/blob/master/F-FrontEnd/test/testdata/contains.f90

So if you try to execute several time the following command, I have segmentation fault. 
`F_Front contains.f90`
When I don't have segmentation fault, the name of the `functionCall` element can be wrong.

``` xml
<functionCall type="FnumericAll">
  <name type="F7f9c88409170">func</name>
</functionCall>
```

instead of this

``` xml
<functionCall type="FnumericAll">
  <name type="F7f9c88409170">hoge</name>
</functionCall>
```

I located the origin of this bug here: 
https://github.com/omni-compiler/omni-compiler/blob/master/F-FrontEnd/src/F-second-pass.c#L626

The ID is freed but it is potentially still referenced as an ID for a function call. I didn't really understand what is done in the second pass so I couldn't fix the bug myself. 

I think this problem occurs when the function is used before it's declaration in the file. As it is done in the `contains.f90` test example. 

If someone can give me a brief explanation of what is done in the second-pass, I'll be glad to try to fix this bug. Maybe @h-murai can give me a hint.

**Comment by mitsuhisa-sato** [comment]
Valentine, Could you check it again? Still we have problem?

**Comment by clementval** [comment]
@mitsuhisa-sato Ok, I'll check it today.

**Comment by clementval** [comment]
@mitsuhisa-sato Looks like it is fixed
